### ISSUE TITLE
how to use train_ads.cpp example

### ISSUE THREAD

**Issue by slaweks17** [dmlc/MXNet.cpp#11]
I compiled train_ads.cpp example in Windows directory. To execute it I need to pass a parameter (apparently some data file name), but I can't find any information what it is supposed to be.

**Comment by hjk41** [comment]
The train_ads example requires a large data file. So I just removed it and replaced it with MLP, which is able to run without manually downloading data. Please checkout the latest code and reopen the visual studio solution.
