### ISSUE TITLE
Use static variable to get function once

### ISSUE THREAD

**Issue by tqchen** [dmlc/MXNet.cpp#23]
e.g. in https://github.com/dmlc/MXNet.cpp/blob/master/include/mxnet-cpp/ndarray.hpp#L59

Change function handle to static, and use a first time initialize strategy, so there is no need to get the function again and save this overhead

**Comment by zhangchen-qinyinghua** [comment]
OK.

I am considering an update of MXNET.cpp these days.

**Comment by zhangchen-qinyinghua** [comment]
Done.
https://github.com/dmlc/MXNet.cpp/pull/24
