### ISSUE TITLE
Why are the .h files in MXNet.cpp different from the .h files in MXNet?

### ISSUE THREAD

**Issue by wsybupt** [dmlc/MXNet.cpp#25]
The .h files in MXNet.cpp/include/mxnet-cpp are not all the same as the .h files in mxnet/include/mxnet. For example, the  bash.h in mxnet/include/mxnet define the Context as a struct:

```
struct Context {
  /*! \brief Type of device */
  enum DeviceType {
    kCPU = cpu::kDevMask,
    kGPU = gpu::kDevMask,
    kCPUPinned = 3
...
```

but the bash.h in MXNet.cpp/include/mxnet-cpp doesn't write the Context, but in the ndarray.h file define the Context as a class.

```
class Context {
 public:
  /*!
  * \brief Context constructor
  * \param type type of the device
  * \param id id of the device
  */
  Context(const DeviceType &type, int id) : type_(type), id_(id) {}
...
```

Can you tell me the reason? Thank you!

**Comment by zhangchen-qinyinghua** [comment]
Sorry for the late replying.

In fact, we rewrote `base.h` to avoid including all the mxnet headers.

**Comment by wsybupt** [comment]
@zhangchen-qinyinghua Thank you for replying ！
