### ISSUE TITLE
How can I write an example to train mnist in c++?

### ISSUE THREAD

**Issue by wsybupt** [dmlc/MXNet.cpp#26]
How can I read the mnist data?  I think I should use the mnist iterator, iter_mnist.cc, am I right?
So I need to rewrite the io.h to the MXNet.cpp/include/..?

**Comment by zhangchen-qinyinghua** [comment]
We don't use data iterator for now, you can transform the data directly to a NDArray.
Check the lenet.cpp for example:
https://github.com/dmlc/MXNet.cpp/blob/master/example/lenet.cpp#L74-L77

**Comment by zhangchen-qinyinghua** [comment]
DataIter is now used, please check the example in the new PR https://github.com/dmlc/MXNet.cpp/pull/29
