### ISSUE TITLE
Train.csv 

### ISSUE THREAD

**Issue by tuonion** [dmlc/MXNet.cpp#28]
Hi, where can I get the data sets-'train.csv'?

**Comment by zhangchen-qinyinghua** [comment]
You can get it from kaggle
https://www.kaggle.com/c/digit-recognizer/data

**Comment by zhangchen-qinyinghua** [comment]
The format of train.csv from Kaggle has been changed.
I'll try to upload the data file to some network disk later.

**Comment by zhangchen-qinyinghua** [comment]
New lenet example with MXDataIter is introduced to MXNET.cpp.
Close this issue.
