### ISSUE TITLE
The parameters to Reshape operator

### ISSUE THREAD

**Issue by conopt** [dmlc/MXNet.cpp#32]
Why comment out the shape parameter in https://github.com/dmlc/MXNet.cpp/blob/master/include/mxnet-cpp/op.h#L938 ? Although it's a struct of vector, the encoding scheme for it doesn't change (still `"(d0, d1, ...)"`. So it's ok and straightforward to type it with `Shape`.

**Comment by zhangchen-qinyinghua** [comment]
Yeah, you're right.
I will remove the comment.
