### ISSUE TITLE
A newbie question

### ISSUE THREAD

**Issue by thirdwing** [dmlc/MXNet.cpp#35]
In https://github.com/dmlc/MXNet.cpp/blob/master/example/lenet.cpp#L98-L100 we have

``` cpp
args_map["data"] =
      NDArray(Shape(batch_size, 1, W, H), ctx_dev, false);
args_map["data"] = data_array.Slice(0, batch_size).Copy(ctx_dev);
```

Is there any reason we need two assignments for `args_map["data"]`?

**Comment by zhangchen-qinyinghua** [comment]
No, the first assignment is not needed. We should remove that.
