### ISSUE TITLE
Implement Executor::Reshape() to allow for varying batch sizes

### ISSUE THREAD

**Issue by rzoom** [dmlc/MXNet.cpp#49]
In `include/mxnet-cpp/executor.h` there is a comment to implement the `Executor::Reshape()` method.  I am interested in using different batch sizes during my network's training.

It would be great if someone could please take a look and implement the `Executor::Reshape()` method and provide a code example of how to use this method to change the batch size during training.

Thank you very much!  I'd be happy to test.

**Comment by zhangchen-qinyinghua** [comment]
You should be able to use Reshape as following:

```
auto reshape_sym = Operator("Reshape")
    .SetParam("shape", Shape(-1,3,224,224))
    .SetInput("data", data) 
    .CreateSymbol('reshape_sym');
```
