### ISSUE TITLE
How to setup???

### ISSUE THREAD

**Issue by wuzhijiexia** [dmlc/MXNet.cpp#51]
I don't know how to setup it. Is this ok if we make it directly?

**Comment by dneprDroid** [comment]
Maybe this: 
http://mxnet.io/get_started/setup.html#step-1-build-the-shared-library    ?

**Comment by conopt** [comment]
@wuzhijiexia, mxnet.cpp is header only, which means that you just need to include the headers in your project, do what you want, and link the mxnet library (can be downloaded from https://github.com/dmlc/mxnet/releases)
