### ISSUE TITLE
mlp example reports segmentation fault error when exits

### ISSUE THREAD

**Issue by flyers** [dmlc/MXNet.cpp#64]
The mlp example here https://github.com/dmlc/MXNet.cpp/blob/master/example/mlp.cpp will not exit normally but complains about a segmentation fault (core dumped) error, probably because some of the resources are not cleaned up. Does anyone know why?
Thanks.

**Comment by mz24cn** [comment]
try calling MXNotifyShutdown() before main() exits.

**Comment by flyers** [comment]
@mz24cn Thanks for your reply. It works.
Besides, I also found the other examples don't work well under the current master mxnet version.
For example, the lenet and googlenet example just give segmentation fault error.

**Comment by flyers** [comment]
@mz24cn In the lenet example, it looks like that the segmentation error starts from the convolution layer construction https://github.com/dmlc/MXNet.cpp/blob/master/example/lenet.cpp#L34-L35

**Comment by mz24cn** [comment]
try copying dmlc/nnvm.git repository latest version into dmlc/mxnet/nnvm directory, then recompile mxnet, rerun the examples.

**Comment by flyers** [comment]
@mz24cn Thanks very much. This issue can be closed now.
